### ISSUE TITLE
could you provide the training code? thanks 

### ISSUE THREAD

**Issue by mumulala** [walktree/libtorch-yolov3#8]

**Comment by walktree** [comment]
Inference only, you could train with darknet or pytorch version.Sent from my iPhone------------------ Original ------------------From: mumulala  <notifications@github.com>Date: Tue,Mar 26,2019 6:28 PMTo: walktree/libtorch-yolov3 <libtorch-yolov3@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [walktree/libtorch-yolov3] could you provide the training code?thanks  (#8)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/walktree/libtorch-yolov3","title":"walktree/libtorch-yolov3","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/walktree/libtorch-yolov3"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"could you provide the training code? thanks  (#8)"}],"action":{"name":"View Issue","url":"https://github.com/walktree/libtorch-yolov3/issues/8"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/walktree/libtorch-yolov3/issues/8",
"url": "https://github.com/walktree/libtorch-yolov3/issues/8",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
